# ===================================
# Common settings (applied to all envs)
# ===================================
spring:
  # This makes 'dev' the default profile if none is set
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: epam

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operationsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

# ===================================
# DEV profile - real settings
# ===================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/training_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
  sql:
    init:
      mode: never

logging:
  level:
    org.flywaydb: DEBUG

# ===================================
# PROD profile - mocked settings
# ===================================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://prod-db-host:5432/training_db
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  flyway:
    baseline-on-migrate: false
    out-of-order: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
  sql:
    init:
      mode: never

logging:
  level:
    org.flywaydb: INFO

# ===================================
# TEST profile - mocked settings
# ===================================
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
  sql:
    init:
      mode: never

logging:
  level:
    org.flywaydb: INFO